In [1]:
from FoodRatingDataSet import FoodRatingDataset

SEQ_LEN = 5

data_set = FoodRatingDataset()

#Test
from Final_Project_Test.TestDataSet import TestDataset
data_set = TestDataset()

NUM_ING = data_set.NUM_ING
OTHER_FEATURES = data_set.OTHER_FEATURES
NUM_RECIPES = data_set.NUM_RECIPES

(<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 2, 3, 4, 5]])>, <tf.Tensor: shape=(1, 5, 20), dtype=float32, numpy=
array([[[1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
         1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
         0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         1., 0., 1., 0.]]], dtype=float32)>, <tf.Tensor: shape=(1, 5, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 5,  8,  9],
        [ 6,  2, 10],
        [ 5,  8,  1],
        [ 7,  6,  9]]])>)


In [2]:
from FoodRecommenderModelSequence import FoodRecommenderModelSequence
import tensorflow as tf
import keras

ids, ing, ofe = tf.keras.Input(shape=[SEQ_LEN]), tf.keras.Input(shape=[SEQ_LEN, NUM_ING]), tf.keras.Input(
    shape=[SEQ_LEN, OTHER_FEATURES])

x = FoodRecommenderModelSequence(recipe_count=NUM_RECIPES, seq_len=SEQ_LEN)((ids, ing, ofe))

mod = keras.Model((ids, ing, ofe), x)
mod.summary()

x_id_pre: Tensor("food_recommender_model_sequence/recipe_embedding/embedding/embedding_lookup/Identity_1:0", shape=(None, 5, 32), dtype=float32)
POS_emb: Tensor("food_recommender_model_sequence/recipe_embedding/embedding_1/embedding_lookup/Identity_1:0", shape=(5, 32), dtype=float32)
x_id: Tensor("food_recommender_model_sequence/recipe_embedding/add/add:0", shape=(5, 5, 32), dtype=float32)
x_ing: Tensor("food_recommender_model_sequence/recipe_embedding/dense/BiasAdd:0", shape=(None, 5, 128), dtype=float32)
x_o: Tensor("food_recommender_model_sequence/recipe_embedding/dense_1/BiasAdd:0", shape=(None, 5, 16), dtype=float32)
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 5)]          0           []                               
                                                          

In [3]:
%load_ext tensorboard

In [4]:
from tensorflow.keras.callbacks import TensorBoard
import time

data = data_set.data()

mod = FoodRecommenderModelSequence(recipe_count=NUM_RECIPES, seq_len=SEQ_LEN)
mod.compile(loss=tf.keras.losses.MeanSquaredError(), optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), metrics=['accuracy'])

tensorboard = TensorBoard(log_dir=f"logs/recommend_{int(time.time())}")
#mod.fit(data, label, epochs=10, validation_split=0.3, callbacks=[tensorboard])
mod.fit(data, epochs=10, callbacks=[tensorboard])

Epoch 1/10
DATA:
X: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 5) dtype=int32>, <tf.Tensor 'IteratorGetNext:1' shape=(None, 5, 20) dtype=float32>, <tf.Tensor 'IteratorGetNext:2' shape=(None, 5, 3) dtype=int32>)
Y: Tensor("IteratorGetNext:3", shape=(None,), dtype=int32)
x_id_pre: Tensor("food_recommender_model_sequence_1/recipe_embedding_1/embedding_2/embedding_lookup/Identity_1:0", shape=(None, 5, 32), dtype=float32)
POS_emb: Tensor("food_recommender_model_sequence_1/recipe_embedding_1/embedding_3/embedding_lookup/Identity_1:0", shape=(5, 32), dtype=float32)
x_id: Tensor("food_recommender_model_sequence_1/recipe_embedding_1/add_3/add:0", shape=(5, 5, 32), dtype=float32)
x_ing: Tensor("food_recommender_model_sequence_1/recipe_embedding_1/dense_6/BiasAdd:0", shape=(None, 5, 128), dtype=float32)
x_o: Tensor("food_recommender_model_sequence_1/recipe_embedding_1/dense_7/BiasAdd:0", shape=(None, 5, 16), dtype=float32)
DATA:
X: (<tf.Tensor 'IteratorGetNext:0' shape=(None, 5) dtype=int32>, <

InvalidArgumentError:  ConcatOp : Dimensions of inputs should match: shape[0] = [5,5,32] vs. shape[1] = [1,5,128]
	 [[node food_recommender_model_sequence_1/recipe_embedding_1/concatenate_1/concat
 (defined at C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\backend.py:3224)
]] [Op:__inference_train_function_2655]

Errors may have originated from an input operation.
Input Source operations connected to node food_recommender_model_sequence_1/recipe_embedding_1/concatenate_1/concat:
In[0] food_recommender_model_sequence_1/recipe_embedding_1/add_3/add (defined at C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\layers\merge.py:256)	
In[1] food_recommender_model_sequence_1/recipe_embedding_1/dense_6/BiasAdd (defined at C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\layers\core\dense.py:210)	
In[2] food_recommender_model_sequence_1/recipe_embedding_1/dense_7/BiasAdd:	
In[3] food_recommender_model_sequence_1/recipe_embedding_1/concatenate_1/concat/axis:

Operation defined at: (most recent call last)
>>>   File "C:\Users\Arne\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "C:\Users\Arne\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
>>>     app.start()
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\kernelapp.py", line 677, in start
>>>     self.io_loop.start()
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "C:\Users\Arne\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
>>>     self._run_once()
>>> 
>>>   File "C:\Users\Arne\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
>>>     handle._run()
>>> 
>>>   File "C:\Users\Arne\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\kernelbase.py", line 457, in dispatch_queue
>>>     await self.process_one()
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\kernelbase.py", line 446, in process_one
>>>     await dispatch(*args)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\kernelbase.py", line 353, in dispatch_shell
>>>     await result
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\kernelbase.py", line 648, in execute_request
>>>     reply_content = await reply_content
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\ipkernel.py", line 353, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\interactiveshell.py", line 2914, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\interactiveshell.py", line 2960, in _run_cell
>>>     return runner(coro)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3377, in run_ast_nodes
>>>     if (await self.run_code(code, result,  async_=asy)):
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "C:\Users\Arne\AppData\Local\Temp/ipykernel_4228/3693155092.py", line 11, in <module>
>>>     mod.fit(data, epochs=10, callbacks=[tensorboard])
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\training.py", line 1216, in fit
>>>     tmp_logs = self.train_function(iterator)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\training.py", line 878, in train_function
>>>     return step_function(self, iterator)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\training.py", line 867, in step_function
>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\training.py", line 860, in run_step
>>>     outputs = model.train_step(data)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\Final_Project_Test\FoodRecommenderModelSequence.py", line 42, in train_step
>>>     y_pred = self(x, training=True)  # Forward pass
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\Final_Project_Test\FoodRecommenderModelSequence.py", line 22, in call
>>>     x = self.embedding(inputs, positional=True)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\Final_Project_Test\RecipeEmbedding.py", line 45, in call
>>>     x = self.concat([x_id, x_ing, x_o])
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\engine\base_layer.py", line 1083, in __call__
>>>     outputs = call_fn(inputs, *args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\layers\merge.py", line 183, in call
>>>     return self._merge_function(inputs)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\layers\merge.py", line 528, in _merge_function
>>>     return backend.concatenate(inputs, axis=self.axis)
>>> 
>>>   File "C:\Users\Arne\PycharmProjects\iannwtfael\venv\lib\site-packages\keras\backend.py", line 3224, in concatenate
>>>     return tf.concat([to_dense(x) for x in tensors], axis)
>>> 

In [ ]:
%tensorboard --logdir logs

In [ ]:
from FoodRecommenderModel import FoodRecommenderModel
import tensorflow as tf
import keras

ids, ing, ofe = tf.keras.Input(shape=[SEQ_LEN]), tf.keras.Input(shape=[SEQ_LEN, NUM_ING]), tf.keras.Input(
    shape=[SEQ_LEN, OTHER_FEATURES])
tar_id, tar_ing, tar_ofe = tf.keras.Input(shape=[1]), tf.keras.Input(shape=[1, NUM_ING]), tf.keras.Input(
    shape=[1, OTHER_FEATURES])

x = FoodRecommenderModel()(((ids, ing, ofe), (tar_id, tar_ing, tar_ofe)))

mod = keras.Model((ids, ing, ofe, tar_id, tar_ing, tar_ofe), x)
mod.summary()


In [ ]:
from FoodRecommenderModelSelfAttention import FoodRecommenderModelSelfAttention
import tensorflow as tf
import keras

ids, ing, ofe = tf.keras.Input(shape=[SEQ_LEN]), tf.keras.Input(shape=[SEQ_LEN, NUM_ING]), tf.keras.Input(
    shape=[SEQ_LEN, OTHER_FEATURES])
tar_id, tar_ing, tar_ofe = tf.keras.Input(shape=[1]), tf.keras.Input(shape=[1, NUM_ING]), tf.keras.Input(
    shape=[1, OTHER_FEATURES])

x = FoodRecommenderModelSelfAttention()(((ids, ing, ofe), (tar_id, tar_ing, tar_ofe)))

mod = keras.Model((ids, ing, ofe, tar_id, tar_ing, tar_ofe), x)
mod.summary()
